### ISSUE TITLE
Chat view is not scrolling to the end of the convo

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#245]
It stops about 3 messages up from the last message (Version 1.1.13 (63))

**Comment by cstiens** [comment]
Fixed in latest.

**Comment by chrisballinger** [comment]
@N-Pex Where is the commit that fixes this? It's not fixed upstream yet so that would be great to merge.
