### ISSUE TITLE
Pending approval

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#350]
@N-Pex We still have a pending approval bug lingering. The scenario is — An Android friend adds me. I'm on iOS and accept the friend request. But, after accepting, the UI in the chat with them showing 'pending approval'. Even after the OTR and OMEMO keys show up for the contact, the pending approval screen still shows.

I force quit, then reopened Zom, and it's still pending approval. My Android contact only has one key for me. I have both for her. Finally, my Android contact verified me, and I got a notification on iOS saying we're now friends. The pending approval went away and we can chat now.

@n8fr8 The Android contact still only has one key for me. On iOS, it says I'm using OMEMO.

**Comment by n8fr8** [comment]
I updated the Android UI so it only shows one key. If it has Omemo, it will show that key. If it doesn't, it will show the OTR key. I think, in the Zom context, it only make sense to show the current relevant key.

Otherwise, I have some thoughts on this issue, and @N-Pex and I can talk through it on the dev scrum tomorrow.

**Comment by N-Pex** [comment]
@n8fr8 I looked at this and could repro on my server. I see that we end up with the iOS end having a subscription request still "pending", i.e. it seems like the Android side never auto answers with a "subscribed" on the request we send from iOS after having approved the initial request from Android. Let's talk later.

**Comment by cstiens** [comment]
@N-Pex @n8fr8 What is the status of this bug? In our tests today (July 17), we still see it.

**Comment by N-Pex** [comment]
@cstiens I am a little confused, I think you mentioned that you DON'T see this anymore, that there's just a problem on iOS<->iOS now (related to migration)? Anyway, to me this seems fixed in the latest Android RC2, I can't reproduce it anymore! =)

**Comment by n8fr8** [comment]
I cannot reproduce between Android and iOS either.

One thing @cstiens were you testing the testflight iOS build or app store? As I discovered, our app store update was rejected due to out of date screenshots.

**Comment by cstiens** [comment]
I'm still seeing this bug. Our fellows who have recently joined us for testing have experienced it too. In every case, it is when an android and iphone become friends. @n8fr8

**Comment by cstiens** [comment]
With the new pending approval UI, we seem to be able to solve this problem when users get stuck here. I'm going to go ahead and close this one. :o
