### ISSUE TITLE
Weird chat views

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#478]
**Weird spacing**
![img_08172377282c-1 2](https://user-images.githubusercontent.com/30634981/32629181-f424b8d6-c55d-11e7-998d-8d626c7edc3f.jpeg)

**No chat history although they've been friends and chatted for years!**
![img_05bbc4cdddd2-1](https://user-images.githubusercontent.com/30634981/32629193-fcad790c-c55d-11e7-9b41-4830e72315ec.jpeg)

**No avatars showing. Also, conference ID showing instead of user ID.**
![img_7f1b5d4a8785-1](https://user-images.githubusercontent.com/30634981/32629201-03aed7e6-c55e-11e7-80d8-5f1a2059fb4e.jpeg)

Device: iPhone SE
App version: 107

**Comment by N-Pex** [comment]
This https://github.com/ChatSecure/ChatSecure-iOS/pull/896 should fix problems 1 and 2, problems 3 should already be fixed in latest version, so we need to retest please.

**Comment by tiffrobo** [comment]
@N-Pex I haven't seen #3 happening with the avatars anymore. However, #1 and #2 are still appearing. Plus a few more additions.

 **'+' and audio button white out.** 

![img_efc26a6bd9b4-1](https://user-images.githubusercontent.com/30634981/34113782-6eb3c9b6-e3d6-11e7-886a-16e9f31e1edd.jpeg)

**Chat bubble distortion**
![img_d8482d22c3b6-1](https://user-images.githubusercontent.com/30634981/34114573-c26ccf2e-e3d8-11e7-8c6d-f755af31657d.jpeg)

![img_a87231be15f7-1](https://user-images.githubusercontent.com/30634981/34113818-9423309c-e3d6-11e7-9197-41bf27e28242.jpeg)

**Overlapping chats**
![img_ff9fde6f48a5-1](https://user-images.githubusercontent.com/30634981/34113843-adba4234-e3d6-11e7-9f05-cf541ef163f1.jpeg)

**Not even sure**
![img_2d710f920400-1](https://user-images.githubusercontent.com/30634981/34113987-13af7532-e3d7-11e7-99d1-f9b2db14592a.jpeg)

**Empty chat view.**
![img_5fd253944108-1](https://user-images.githubusercontent.com/30634981/34114451-72327e50-e3d8-11e7-8df1-cd6a22121095.jpeg)

**Limited chat views with disappearing conversations.** 
![img_11aa47af8f4e-1](https://user-images.githubusercontent.com/30634981/34114705-12ca469a-e3d9-11e7-96f5-4736a3b44f40.jpeg)

**No error and no checks on sent message**
![img_0af5453edced-1](https://user-images.githubusercontent.com/30634981/34114663-f850c5f0-e3d8-11e7-9094-702130ee4862.jpeg)

Messages cut off.
![img_b0c4f40516bc-1](https://user-images.githubusercontent.com/30634981/34115220-990cf436-e3da-11e7-8a2c-8f39d5bdaeed.jpeg)


Device: iPhone 7 aqnd iPhone SE
App Version: Build 112 and 113
