### ISSUE TITLE
Group invite screen showing for existing groups

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#576]
The "new group" flag should only be set on new groups added to, not for all your existing groups

**Comment by tiffrobo** [comment]
I am also seeing the overlay reappear after you've joined a newly created group (see the steps taken below). 
It doesn't happen every time, but frequent enough. 

Steps:
You've joined a new group, close the group view, back to your convo view and then come back to the group, the invite reappears. 
Not every time, but frequently enough.

Device: iPhone7, iPad, iPhone6
App version: 127

**Comment by cstiens** [comment]
Fixed in next build

**Comment by tiffrobo** [comment]
Fixed.

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129

**Comment by N-Pex** [comment]
I think this still happens on groups you yourself create(?). I need to check.

**Comment by tiffrobo** [comment]
Yes, @N-Pex  I'm still seeing an initial Group Invite screen when you create a group and it opens the first time. 

Device: iPhone 6, iPhone 7, iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129

**Comment by N-Pex** [comment]
Should be fixed in build 130.

**Comment by tiffrobo** [comment]
No longer seeing this.

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 130
